### ISSUE TITLE
Support inline variables in format strings

### ISSUE THREAD

**Issue by intgr** [WiSaGaN/simple-error#19]
It seems inline variables in format strings are not supported, e.g.

```rust
fn x() -> Result<(), Box<dyn Error>> {
    let msg = "test";
    bail!("Message: {msg}");
}
```

Will be reported with message literally "Message: {msg}" instead of expected "Message: test"

**Comment by WiSaGaN** [comment]
Glad to take PR for it!

**Comment by WiSaGaN** [comment]
Fixed in https://github.com/WiSaGaN/simple-error/commit/1920434e45163774a4e24909a7b9abb209afe123

@intgr can you help test it?

**Comment by intgr** [comment]
Awesome, thanks! Seems to work in https://github.com/intgr/ego/pull/119
