### ISSUE TITLE
Missing .into() in formatted version of bail! results in unboxable error

### ISSUE THREAD

**Issue by rix0rrr** [WiSaGaN/simple-error#5]
The following compiles:

```
fn something() -> Result<(), Box<Error>> {
  bail!("Oops");
}
```

The following does not:

```
fn something() -> Result<(), Box<Error>> {
  bail!("Oops {}", "argument");
}
```

I think it's because of a missing `.into()` in this line:

https://github.com/WiSaGaN/simple-error/blob/master/src/lib.rs#L268

**Comment by WiSaGaN** [comment]
Thanks for the report! This has been fixed in https://github.com/WiSaGaN/simple-error/commit/196c524f089bc582eedd2af5493658cfe9412bd5. I have published 0.1.13 to include this change.
