### ISSUE TITLE
0.1.13 breaks use in try_for_each

### ISSUE THREAD

**Issue by ChrisJefferson** [WiSaGaN/simple-error#6]
This is reduced from some code in my program. This worked in 0.1.12, but breaks in 0.1.13 with the error.

```
  | /     try_with!(
10 | |         std::fs::File::create("cheese"),
11 | |         format!("Oh no")
12 | |     );
   | |______^ cannot infer type for `E`
```

Example program:
```
#[macro_use]
extern crate simple_error;

fn main() -> Result<(), simple_error::SimpleError> {

    let v = vec![1,2,3];

    v.iter().try_for_each(|ref c| {
    try_with!(
        std::fs::File::create("cheese"),
        format!("Oh no")
    );
    Ok(())
    })?;

    Ok(())
}
```

**Comment by WiSaGaN** [comment]
Hmm, seems that we need to yank 0.1.13, and release 0.2.0?

**Comment by ChrisJefferson** [comment]
I also wasn't really clear what I have to write now, to make my code run in this release? This is unfortunately beyond my understanding of Rust...

**Comment by WiSaGaN** [comment]
Since `rustc` cannot infer the correct type between `try_with` and `?`, we will need to specify the return type of the closure.
One way to do this is to replace the return type in the closure inside the `try_for_each`
from 
`Ok(())` (the first one)
to
`Result::<(), SimpleError>::Ok(())`.

**Comment by WiSaGaN** [comment]
It seems that small inference breakage is usually not treated as breaking backwards compatibility in the community.

**Comment by ChrisJefferson** [comment]
I realise I might not be using rust "well", but I do think this change is going to make the package quite a bit worse for me, having to annotate lots of my Oks... I assume there is some advantage to this breakage for someone else?

**Comment by WiSaGaN** [comment]
The feature was to improve https://github.com/WiSaGaN/simple-error/issues/5 situation.
I can yank 0.1.13 and publish it as 0.2.0 instead. It will prevent `cargo update` to automatically upgrade 0.1.12 to 0.1.13.
Does that help your situation?

**Comment by WiSaGaN** [comment]
Now 0.1.13 has been yanked and republished as 0.2.0.
